feat(sandbox): make icons searchable by keyword
Kong/icons pull request #322
Opened 2024-06-09 21:01 UTC by mihai-peteu

# Summary

**http://localhost:5173/icons/?q=south** 
<img width="960" alt="Screenshot 2024-06-09 at 13 54 35" src="https://github.com/Kong/icons/assets/103061463/ae611463-cc2e-4986-b62b-1426d6db6773">

**http://localhost:5173/icons/?q=islands** 
<img width="963" alt="Screenshot 2024-06-09 at 13 57 00" src="https://github.com/Kong/icons/assets/103061463/8a62e4dc-964d-4484-b287-a660d64a65a0">

2024-06-11 15:05 UTC, portikM commented on sandbox/pages/HomePage.vue
> +      keyword: '',
I suggest we name it plural (`keywords`) and make it an array. Some other icons could benefit from having multiple search terms defined as keywoards (e.g. CogIcon -> `keywoards: ['gear', 'settings']`). I don't ask you to add keywords to that icon - I just use it as an example as to why array would be more beneficial

2024-06-11 15:05 UTC, portikM commented on sandbox/pages/HomePage.vue
> +      icon?.keyword?.toLowerCase().includes(searchTerm)
If you make `keywords` an array you will have to remove `.toLowerCase()` from here but I suggest you transform all keywords to lowercase when you're adding them to the `keywords` array instead (line 111)

2024-06-17 16:37 UTC, mihai-peteu commented on sandbox/pages/HomePage.vue
> +      keyword: countryMap.has(countryCode) ? countryMap.get(countryCode)?.name : '',
Linter doesn't like it.  A JS Map's `.get()` can still return undefined....

https://www.basedash.com/blog/why-typescript-map-get-returns-undefined#:~:text=USING%20OPTIONAL%20CHAINING

2024-06-18 19:15 UTC, portikM submitted a review, later dismissed

2024-06-18 19:20 UTC, adamdehaven requested changes
I think we’re going to need to make some adjustments to lazy load the icons or something; loading the sandbox takes upwards of 3-4 seconds with all of the flag icons

the search is super-laggy too and needs to be debounced

2024-06-18 19:20 UTC, adamdehaven commented
the lag seems to be related to search; the current site loads pretty quickly

2024-06-18 23:54 UTC, mihai-peteu commented
@adamdehaven the search input was already debounced, i lowered the timeout from 500ms to 200ms
https://github.com/Kong/icons/pull/322/commits/d58093fe7bb887bdd7e324b97ca819b8b8d290ea#diff-f5b67e1dd2f5e869bf6f35aadae0f59bd40f4f96aaebb91de2b99876e57740e2R50

If you look at my last commit, I think maybe the other reason for the perceived slowness could have been that were were redefining `allComponents` inside of `filteredComponents` every time the search value was changed 😬 

Should be considerably more performant now.

2024-06-19 00:53 UTC, adamdehaven reviewed
The lag is much less noticeable with your latest commit. 

Would it make sense to display the country names under the Flag icon names in the card? Might make it easier to identify the flag you're looking for when searching.

2024-06-19 16:25 UTC, mihai-peteu commented
Updated:

<img width="1074" alt="Screenshot 2024-06-19 at 09 12 35" src="https://github.com/Kong/icons/assets/103061463/50cedc99-db9c-48d4-968e-1b21451f7c4d">

2024-06-19 16:34 UTC, adamdehaven approved these changes

2024-06-19 19:14 UTC, merged